# Generated by Django 4.1.7 on 2023-03-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('catno', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('release_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('listed', models.DateTimeField()),
                ('comments', models.TextField()),
                ('media_condition', models.CharField(max_length=20)),
                ('sleeve_condition', models.CharField(max_length=20)),
                ('accept_offer', models.BooleanField()),
                ('external_id', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('format_quantity', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
